---
- hosts: all
  tasks:
    - name: install system packages
      sudo: yes
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - python-pip
        - python-virtualenv
        - python-dev
        - python-nose
        - libblas-dev
        - liblapack-dev
        - build-essential
        - gfortran
        - gcc
        - libfreetype6-dev
        - libpng12-dev
        - zlib1g-dev
        - libgtk2.0-dev
        - libzmq-dev
        - libatlas-dev
    - name: install python packages
      pip: name={{ item }} state=present virtualenv=/tmp/mltooling extra_args="-U"
      with_items:
        - tornado
        - pyzmq
        - pygments
        - numpy
        - pillow
        - matplotlib
        - scipy
        - pandas
        - requests
        - beautifulsoup4
        - praw
        - gensim
        - scikit-learn
